create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  part_number text not null unique,
  material_name text,
  vendor text,
  material_contact text not null,
  team_contact text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists materials_part_number_idx
  on public.materials(part_number);

alter table public.materials enable row level security;

-- 웹 서버는 service role key로 조회하므로 일반 공개 정책을 만들지 않습니다.
-- service role key는 절대로 브라우저 코드에 넣지 마세요.